service: final-aws-node-todo

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ TodosTable, Arn ]
  environment:
    TODO_TABLE: todos-table-${sls:stage}

functions:
  create:
    handler: handler/createTodo.createTodo
    events:
      - http:
          path: todos
          method: post
          cors: true
  list:
    handler: handler/listTodos.listTodos
    events:
      - http:
          path: todos/list
          method: get
          cors: true
  get:
    handler: handler/getTodo.getTodo
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: todos-table-${sls:stage}